name: AutoBuild.yml

on:
  push:
    branches-ignore:
      - master
      
jobs:
  build:
    name: AutoBuild on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Pack release version
      run: dotnet pack --configuration Release
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push bin/Release/frendstask.*.nupkg --api-key ${{ secrets.CommunityFeedApiKey }} --source https://www.myget.org/F/frends-community-test/api/v2/package
