name: BuildUsingLegacyTools

on:
  push:
    branches:    
      - master

jobs:
  build:
    name: ReleaseTheTask
    runs-on: ubuntu-latest
    
    steps:
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source 
      
    - name: Push NuGet package to the (prod) feed
      run: dotnet nuget push Frends.Community.Echo\bin\Release\Frends.Community.Echo.*.nupkg  --api-key ${{ secrets.CommunityProdFeedApiKey }} --source https://www.myget.org/F/frends-community/api/v2/package --symbol-source https://www.myget.org/F/frends-community/symbols/api/v2/package

